version: "3.9"
services:
  app:
    container_name: beancount-gs
    image: toroto/beancount-gs:1.0.0
    ports:
      - "10000:80"
    volumes:
      - "${dataPath:-/data/beancount}:${dataPath:-/data/beancount}"
      - "${dataPath:-/data/beancount}/icons:/app/public/icons"
      - "${dataPath:-/data/beancount}/config:/app/config"
      - "${dataPath:-/data/beancount}/bak:/app/bak"